wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1645634859
    t:
      1:
      - 2
      - 3
      4: 3.9.7
      5: 0.12.7
      8:
      - 1
      - 3
      - 5
