wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1645030158
    t:
      1:
      - 5
      4: 3.9.7
      5: 0.12.7
      8:
      - 3
      - 5
